name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.ruby-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - head
          - jruby
          - truffleruby
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install as gem
        run: |
          rake install
      - name: Test
        run: |
          ruby -run -e mkdir -- tmp
          ruby -run -e cp -- -p -r test tmp
          cd tmp
          ruby ../run-test.rb
